[versions]
agp = "8.13.0"
kableCore = "0.40.0"
kableDefaultPermissions = "0.40.0"
kotlin = "2.2.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.10.01"

[libraries]
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-navigation = { module = "androidx.navigation:navigation-compose", version = "2.9.5" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-adaptive-navigation-suite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite" }
kable-core = { module = "com.juul.kable:kable-core", version.ref = "kableCore" }
kable-default-permissions = { module = "com.juul.kable:kable-default-permissions", version.ref = "kableDefaultPermissions" }
nordicsemi-ble = { module = "no.nordicsemi.android:ble", version = "2.11.0" }
koin-bom = { module = "io.insert-koin:koin-bom", version = "4.1.0" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-annotations-bom = { group = "io.insert-koin", name = "koin-annotations-bom", version = "2.2.0" }
koin-annotations = { group = "io.insert-koin", name = "koin-annotations" }
koin-android-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-android-compose-navigation = { module = "io.insert-koin:koin-androidx-compose-navigation" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version = "2.2.0" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version = "0.37.3" }
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version = "0.4.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "2.2.0-2.0.2" }
